### ISSUE TITLE
Cannot fetching data of message on gui

### ISSUE THREAD

**Issue by Andy320** [kafka-lens/kafka-lens#55]
os: mac 10.14.1
kafka: 2.1.0
console output:
> kafka-lens@0.1.0 start /Users/wenjunwang/git_repo/github/kafka-lens
> electron .

localhost:9092
[ { topic: '__transaction_state',
    partition: 50,
    messages: Promise { 0 } },
  { topic: 'test', partition: 1, messages: Promise { 4 } },
  { topic: '__consumer_offsets',
    partition: 50,
    messages: Promise { 13 } } ]
get msg request received { host: 'localhost:9092', topic: 'test' }

problem:
Topic and partition can be showed up but message hang on "Fetching Data..." on the right of the web page.

**Comment by iAmHarmon** [comment]
Hi Andy,

Did you run Kafka Lens prior to this run? As messages are being consumed, they are also being committed which may be why you are experiencing this issue. I suggest having at least one topic with data actively being produced in order for kafka lens to work effectively.

Cheers!
