### ISSUE TITLE
npm start is failing with "cannot open display"

### ISSUE THREAD

**Issue by ayush-chauhan** [kafka-lens/kafka-lens#61]
Hi,

I am getting the following error 

> kafka-lens@0.1.0 start /home/centos/kafka-lens
> electron .

(electron:21024): Gtk-WARNING **: 15:30:28.679: cannot open display: 

npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! kafka-lens@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kafka-lens@0.1.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kafka-lens package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kafka-lens
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kafka-lens
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/centos/kafka-lens/npm-debug.log

**Comment by smrititripathi027** [comment]
Getting same issue. How to solve this ?

**Comment by nahuelarjonadev** [comment]
The project has been completely revamped in version 2. The usage of yarn is strongly encouraged! This issue among several others shouldn't be there anymore
