### ISSUE TITLE
npm start issue

### ISSUE THREAD

**Issue by smrititripathi027** [kafka-lens/kafka-lens#65]
When running npm start command, following output is coming. How to solve this ?

> kafka-lens@0.1.0 start /home/kafka-lens/kafka-lens-master
> electron .

(electron:18555): Gtk-WARNING **: 11:54:47.723: cannot open display:

npm ERR! Linux 3.10.0-693.17.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! kafka-lens@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kafka-lens@0.1.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kafka-lens package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kafka-lens
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kafka-lens
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/kafka-lens/kafka-lens-master/npm-debug.log

**Comment by nahuelarjonadev** [comment]
The project has been completely revamped in version 2. The usage of yarn is strongly encouraged!
